name: "Continuous Integration"

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  
jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Check formatting
        run: |
          cargo fmt -- --check

  wasm-tests:
    name: WASM tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Setup WASM tooling
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli
          cargo install wasm-pack

      - name: Test WASM lib with pure-rust backend
        run: wasm-pack test --node --no-default-features --features "crypto_pure_rust" --lib

      - name: Test WASM offline integration with pure-rust backend
        run: wasm-pack test --node --no-default-features --features "crypto_pure_rust" --test offline

      - name: Test WASM online integration with pure-rust backend
        continue-on-error: true
        run: wasm-pack test --node --no-default-features --features "crypto_pure_rust" --test online

  native-openssl:
    name: Native openssl lib tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Test lib with openssl backend
        run: cargo test --no-default-features --features "crypto_openssl" --lib -- --nocapture

  native-pure-rust:
    name: Native pure-rust tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Test lib with pure-rust backend
        run: cargo test --no-default-features --features "crypto_pure_rust" --lib -- --nocapture

      - name: Test offline integration with pure-rust backend
        run: cargo test --no-default-features --features "crypto_pure_rust" --test offline -- --nocapture

      - name: Test online integration with pure-rust backend
        continue-on-error: true
        run: cargo test --no-default-features --features "crypto_pure_rust,online" --test online -- --nocapture
